name: Rust

on:
  push:
    branches: [ "dev" ]

permissions:
  contents: write

jobs:
  build_release:
    strategy:
      matrix:
        target:
            - x86_64-unknown-linux-musl     
            - x86_64-pc-windows-gnu
            - x86_64-apple-darwin
        include:
            - target: x86_64-unknown-linux-musl
              os: ubuntu-latest
            - target: x86_64-pc-windows-gnu
              os: windows-latest
            - target: x86_64-apple-darwin
              os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true
        
    - name: Install Cross
      if: matrix.os == 'ubuntu-latest'
      run: cargo install cross

    - name: Build
      run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            cross build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi

    - name: Archive release binaries
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.target }}
        path: |
            target/${{ matrix.target }}/release/*
